#!/bin/bash

cat Main.hs \
  | awk '/Start Interface/,/End Interface/' \
  | grep '\->\|getLine' \
  | cut -c 13- \
  | grep -v "TODO" \
  | sed 's/_/other key/' \
  | sed 's/-- //' \
  | sed 's/case c of /input one:/' \
  | sed 's/getLine/Enter characters ending with an enter key/'
