#!/bin/bash

cat Main.hs \
  | awk '/Start Interface/,/End Interface/' \
  | grep "['_]"'\s*\->\|getLine' \
  | cut -c 13- \
  | grep -v "TODO" \
  | grep -v "case playing of" \
  | sed 's/_/other key/' \
  | sed 's/-- //' \
  | sed 's/case c of /input one:/' \
  | sed 's/getLine.*$/Enter characters ending with an enter key/' \
  | cat <(echo "### INSTRUCTIONS") <(echo "\`\`\`") - <(echo "\`\`\`")
